### ISSUE TITLE
Segfault for PRISM model where variables are optimized away

### ISSUE THREAD

**Issue by kleinj** [moves-rwth/storm#9]
If I run the attached model with

`bin/storm --prism from_pta.txt`

I get a segmentation fault:

```
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff6188750 in storm::expressions::BaseExpression::getManager (this=0x0) at storm/storm-trunk.github/src/storm/storage/expressions/BaseExpression.cpp:102
102                 return manager;
(gdb) bt
#0  0x00007ffff6188750 in storm::expressions::BaseExpression::getManager (this=0x0) at storm/storm-trunk.github/src/storm/storage/expressions/BaseExpression.cpp:102
#1  0x00007ffff6197b4a in storm::expressions::Expression::getManager (this=0x7fffffff8d80) at storm/storm-trunk.github/src/storm/storage/expressions/Expression.cpp:156
#2  0x00007ffff4fa486b in storm::adapters::Z3ExpressionAdapter::translateExpression (this=0x5555558d27f0, expression=...) at storm/storm-trunk.github/src/storm/adapters/Z3ExpressionAdapter.cpp:20
#3  0x00007ffff5eb0b6f in storm::solver::Z3SmtSolver::add (this=0x555555887af0, assertion=...) at storm/storm-trunk.github/src/storm/solver/Z3SmtSolver.cpp:105
#4  0x00007ffff5328655 in storm::generator::PrismNextStateGenerator<double, unsigned int>::getInitialStates(std::function<unsigned int (storm::storage::BitVector const&)> const&) (this=0x555555884e50, stateToIdCallback=...)
    at storm/storm-trunk.github/src/storm/generator/PrismNextStateGenerator.cpp:145
...
```

From a bit of debugging it looks like the variables are optimized away in https://github.com/moves-rwth/storm/blob/13982b41161a96fe42d4b2f66c4d4f938eeff3e2/src/storm/storage/prism/Program.cpp#L1240
and then in
https://github.com/moves-rwth/storm/blob/13982b41161a96fe42d4b2f66c4d4f938eeff3e2/src/storm/storage/prism/Program.cpp#L456
the `result` expression does not get initialized, as there are no variables anymore.

I guess it would suffice to return a `true` expression if there are no variables in that function?

Test case from https://github.com/prismmodelchecker/prism-tests/blob/master/bugfixes/ptaalphabet.nm, translated using PRISM's digital clock conversion.

Model: [from_pta.txt](https://github.com/moves-rwth/storm/files/1257569/from_pta.txt)

**Comment by kleinj** [comment]
Fix looks good, thanks.
